### ISSUE TITLE
Authnrequest

### ISSUE THREAD

**Issue by altounsi** [rasmusson/webprofile-ref-project#2]
Do you know whew I can do SAML request authentication using java something similar to this  https://www.samltool.com/validate_authn_req.php

**Comment by rasmusson** [comment]
Im not sure what it is that you wan to do, but I have written a book on how to use the Java OpenSAML library to do SAML authentication.
It is availible for OpenSAML V3 [here](https://blog.samlsecurity.com/a-guide-to-opensamlv3.html) and OpenSAML V2 [here](https://blog.samlsecurity.com/a-guide-to-opensamlv2.html). 

This github project is acctually reference code for the book. 

Good luck!

**Comment by altounsi** [comment]
I just bought your book, and what I want I want to do is: I will be a partner to some Idp, I have to receive SAML2 request from the SP then I have to validate the SAML request in terms of everything for example signature , time, Issuer .. etc. do you have a code to validate the request that comes from the SP.

**Comment by rasmusson** [comment]
Part III: Chapter 2 discusses message verification

**Comment by altounsi** [comment]
Dear Rasmusson, 
Part III: Chapter 2: discuses two things "Signing a Message" and "Verifying a Signature", AS IdP, the only thing is useful to me is "Verifying a Signature". but you have not talked about other things that is very important to the IdP to validate such as: 
how to validate Target URL, Destination of the AuthN Request,SP EntityId. timestamps, is it post or redirect, validate SAML version, these kind of things that I was looking in your book. I would appreciate if you help me in this matter.

**Comment by rasmusson** [comment]
Yes as I write in the book description, this book is focused on the SP
side, but I can try to give som guidance.
Target URL is not covered by SAML but you should validate that this is a
valid URL in you environment.
Destination of the authn request should be the URL of your recieving
endpoint. Could be validated using  ReceivedEndpointSecurityHandler
SP EntityId should be the entity Id of the SP as argreed upon when
registering the SP.
Timestamps could be validating using MessageLifetimeSecurityHandler.
About redirect and post, if your using HTTP request object you should be
able to get this by using getMethod

Both ReceivedEndpointSecurityHandler and MessageLifetimeSecurityHandler are
discussed under "Summary of migration process" - "Massage Handlers"

--
Stefan
